### ISSUE TITLE
Signal Without Initial Value

### ISSUE THREAD

**Issue by sirinath** [JuliaLang/Reactive.jl#112]
Having to specify an initial dummy value can adversely affect subsequent calculation.

**Comment by SimonDanisch** [comment]
you can do this:
```Julia
map(f, signal, init=value)
```
which results in f getting called only when the first real value gets pushed ;)

**Comment by SimonDanisch** [comment]
Or are you talking about `foldp`?

**Comment by SimonDanisch** [comment]
Disregard my comment, I completely missed your point ;)
This is the work around for `f` to be never called with the dummy value!

**Comment by sirinath** [comment]
OK. But why have to give it in the 1st place?

**Comment by sirinath** [comment]
But `value` will give another dummy

**Comment by shashi** [comment]
You can use channels if you want no initial value.

There's not really a variant of Signal without initial value.

**Comment by shashi** [comment]
You can use a `Signal{Nullable}` here with Nullable{T}() as your initial value. This way you can be sure that you have thoroughly handled the case where the initial value is not available.

**Comment by sirinath** [comment]
Will this have a performance penalty?

**Comment by sirinath** [comment]
See http://reactors.io/ RCell this does just this.

**Comment by shashi** [comment]
No, the performance cost will be a couple of nanoseconds.

**Comment by sirinath** [comment]
If you have to respond at sub microsecond speeds nanoseconds can add up if you chain many signals.
