### ISSUE TITLE
Feature Request: De/Attachable Subgraphs

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/Reactive.jl#24]
Hi,
I've been speaking about this with Shashi, but I think so far I haven't had good examples, so the conclusion was mostly, that I'm using react wrong.
I did some more thinking, and I came to the conclusion, that we really need some mechanisms, to connect different react graphs, as you can't always construct the whole graph.
Example:
In an API I want to offer, to make a shader out of some string signal. But at shader creation, I don't want to force the user to decide, from which string signal he wants to create the shader. 

```Julia
function makeshader(defaultsource::String)
   sourcecode = ascii(defaultsource)
   dummyInput = Input(sourcecode)
   lift(dummyInput) do sourcecode
      ... Make new shader
      ... Delete old shader
      return shader
   end
   return dummyInput # return "socket" to which one can connect
end
# At initializsation, by some API, somewhere, where the user has no access
shader = makeshader(SomeShaderSource)

# At a different time point, user wants to interact with the shader, namely updating it
newsource = lift(x -> readall(open("filename")), every(1.0)) # this is just exemplary and a really wasteful way of doing this

# Now, this doesn't work in the current API:
lift(x-> push!(shader, x), newsource)
# So something like this is needed!?
connect(shader.dummyInput, newsource)
```
Another example:
I'm working on widgets for my plots.
The data for a plot in GLPlot looks a little like this:
```Julia
[
:attributename => Input(someValue)
:attributname => SomeLift
....
]
``` 
Now, at the part where I initialize this datastructure, I don't even remotely know, if the person wants to change the value via a my glwidgets, via the commandline with push!(), or if someone builds, for example, some tk wrapper.

Best,
Simon

**Comment by shashi** [comment]
@SimonDanisch I just PR'd an implementation of `flatten` which turns out works exactly the way @baconscript describes :)

However, I am of the opinion that this must be used sparingly for simplicity.

**Comment by shashi** [comment]
Now that we have flatten and even `bind!` and `unbind!`. I guess we can close this...
