### ISSUE TITLE
Signal difference error in tutorial example

### ISSUE THREAD

**Issue by multidis** [JuliaLang/Reactive.jl#33]
Difference code from the [introduction](http://julialang.org/Reactive.jl/) results in bounds error. When this line

    diff = lift(x->x[1], foldl(difference, 0.0, signal))

is modified by providing a tuple as the initial fold value instead

    diff = lift(x->x[1], foldl(difference, (0.0, 0.0), s))

then everything seems to work.

**Comment by shashi** [comment]
Oh thanks! Yes, tuple the initial value must be a tuple. I will fix this in the docs soon.

**Comment by multidis** [comment]
After `lift` API change from this [commit](https://github.com/JuliaLang/Reactive.jl/commit/62324a60c11137147344c43c2b454ca9ce085156) on there are even more changes to be made. Took me some time to trace how `lift` changed - would really help to update the documentation examples.
