### ISSUE TITLE
Zip | Unzip | Map | FlatMap - Higher order functions

### ISSUE THREAD

**Issue by sirinath** [JuliaLang/Reactive.jl#34]
Can you provide higher order functions. E.g. zip function to covert a structure of Reactive variables to a reactive stream of the structure

**Comment by shashi** [comment]
`zip` is redundant `lift(tuple, x, y, z)` would do the trick.

for `flatten` you need the branch called `flatten` it's a work in progress. You can flatten a signal of signal to make it behave like a single signal.
