### ISSUE TITLE
Data timing / windowing / buffering function

### ISSUE THREAD

**Issue by sirinath** [JuliaLang/Reactive.jl#35]
It is helpful to have function which:

 - Emit last value every n seconds if no new values
 - If there is multiple updates with the gap between the updates which are less than a threshold ignore and send last value in the cluster of updates
 - etc.

See:
http://reactivex.io/
https://github.com/GPars/GPars
http://hopac.github.io/Hopac/Hopac.html
https://github.com/reactor/reactor

**Comment by shashi** [comment]
For the first one you can:

`sampleon(every(n), signal)`

I have plans to add windowing and throttling a PR is welcome though

**Comment by shashi** [comment]
There is now `throttle` which can be used to get the same effect as `throttle` and `window` in Rx as far as I can tell

If there are more neat things that are worth having, please open a new issue.
