### ISSUE TITLE
No getindex method defined for Input

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/Reactive.jl#37]
````julia
julia> sensor_input = Input([0.0, 1.0, 0.0]) 
3-element Array{Float64,1}:
 0.0
 1.0
 0.0

julia> left_motor  = @lift sensor_input[1] - sensor_input[3]
ERROR: MethodError: `getindex` has no method matching getindex(::Reactive.Input{Array{Float64,1}}, ::Int64)
 in anonymous at no file
 in lift at no file
````

**Comment by shashi** [comment]
this is a bug with the `@lift` macro, could you for now use the long-form lift function call?

**Comment by milktrader** [comment]
````julia
julia> left_motor  = lift(sensor_input[1] - sensor_input[3])
ERROR: MethodError: `-` has no method matching -(::Reactive.Input{Float64}, ::Reactive.Input{Float64})
````
There still is the issue of not having a `getindex` method defined.

**Comment by shashi** [comment]
That would be
```julia
julia> left_motor  = lift((input) -> input[1] - input[3], sensor_input)
```
:)

**Comment by milktrader** [comment]
Well, I didn't notice that there is a `-` method missing error in that example.

**Comment by milktrader** [comment]
Ah, that's it. Thanks.

**Comment by shashi** [comment]
Oh, wait, there is a bug here.

**Comment by milktrader** [comment]
My first hack was to do this:

````julia
julia> function Base.getindex{T<:Input}(I::T, n::Int64)
       Input(I.value[n])
       end
````
But I'm not sure about what havoc that would wreak upon the underlying assumptions of how updates would work.

**Comment by milktrader** [comment]
For my purposes, that hack works. I don't want to clutter this issue with the example so I provide it here in a [gist](https://gist.github.com/milktrader/97d96b51b53eec747a19)

**Comment by shashi** [comment]
I would do this:
```julia
julia> initial_buy = (100,90.00)
(100,90.0)
julia> buysome = Input(initial_buy)
(100,90.0)
julia> bot_some = lift(A, buysome) do fa, buy
    qty, fill = buy
    transact(fa,qty,fill)
end

```

**Comment by milktrader** [comment]
Ah, thanks! I would close this since I was using the package not as it is designed. But you mentioned a new bug, so I'll let you close it.

**Comment by shashi** [comment]
I was referring to the `@lift` bug in your first comment.

**Comment by milktrader** [comment]
Ah, okay. Looks like I took this issue down a different path but now we're back where we started so I'll leave it open.

**Comment by shashi** [comment]
The `@lift` macro has been removed :)
