### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/Reactive.jl#38]
In the __Maintaining State__ section a copy-paste of the `leading` definition generates an error

````julia
julia> leading = lift((a, b) -> if a > b ? :Alice : a < b ? :Bob : :Tie, alice, bob)
ERROR: syntax: unexpected ,
````

**Comment by shashi** [comment]
Oh I see, the if was unnecessary.

**Comment by milktrader** [comment]
Ha, I stared at that expression for as long as I did and didn't see that. 

Yeah, that was it. 

This is also a good use-case for using `do`

````julia
leading = lift(alice, bob) do a, b
       if a > b
           :Alice
       elseif a < b
           :Bob
       else
           :Tie
       end
end
````
