### ISSUE TITLE
RFC: Signal type hell

### ISSUE THREAD

**Issue by shashi** [JuliaLang/Reactive.jl#46]
Passing in the right types to `lift`, `foldl` and `flatten` (and finally resorting to `Any`) in [these lines](https://github.com/shashi/Escher.jl/blob/3aaea4017d9662aa7dd8ceed75e0f934d9ee6077/examples/minesweeper.jl#L41-L48) caused me a *lot* of distress. This was mainly because a signal of type `Board{true}` will not update to `Board{false}`, and you are forced to annotate the type in each node in the subgraph.

This has got me wondering if there is *any* use to having the default type be the tightest possible type depending on the initial value in `lift`, `foldl` and `flatten`. It would be useful if one could statically warn of potential errors due to wrong types, Julia does not do this anyway. I am inclining towards using `Any` as default, and making tighter types as opt-in.

Also need consistency in the API for specifying types. I am thinking a `typ` keyword argument for `lift`, `foldl` and `flatten` can be consistent.

@stevengj @SimonDanisch what do you think of this?

**Comment by shashi** [comment]
With the above commit, I was able to get away with: https://github.com/shashi/Escher.jl/blob/e47332d4db89940596c01a9f946b75b423518327/examples/minesweeper.jl#L41-L47 signal types of `lift`, `foldl` and `flatten` can now be specified with the `typ` kwarg. Suggestions to change this are welcome!

I had to mention the type inside the `foldl` function just once. I am really happy about this! Now to solve #47.

**Comment by dcjones** [comment]
> I am inclining towards using Any as default, and making tighter types as opt-in.

I suppose you could also make tighter types default and opt-in for looser types, but I'm guessing the performance difference isn't a big deal so this sounds reasonable to me.

**Comment by shashi** [comment]
@dcjones yeah, that's how it is right now (looser types are opt-in). The inconsistency in the API made it seem more complex and confusing. The only open question now is is `typ` a good name for the kwarg.
