### ISSUE TITLE
Pkg.test("Reactive")

### ISSUE THREAD

**Issue by StreetLevel** [JuliaLang/Reactive.jl#53]
Hey guys,

i've tried to install GLPlot but always got the error:

Pkg.test("GLPlot")

ERROR: `lift` has no method matching lift(::Function, ::Type{Vector2{Float64}}, ::Input{Vector2{Float64}}, ::Input{Vector4{Int64}})
 in createwindow at /Users/Max/.julia/v0.3/GLWindow/src/reactglfw.jl:359
 in createdisplay at /Users/Max/.julia/v0.3/GLPlot/src/GLPlot.jl:51
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/Max/.julia/v0.3/GLPlot/test/runtests.jl, in expression starting on line 3

So i did a Pkg.test("Reactive") and got this message:

INFO: Testing Reactive
Basic checks
     - lift
InexactError()

 in push! at /Users/Max/.julia/v0.3/Reactive/src/Reactive.jl:261
 in anonymous at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:178
 in do_fact at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:201
 in anonymous at /Users/Max/.julia/v0.3/Reactive/test/basics.jl:177
 in context at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:341
 in anonymous at /Users/Max/.julia/v0.3/Reactive/test/basics.jl:15
 in facts at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:315
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
     - merge
     - foldl
     - filter
     - sampleon
     - droprepeats
     - dropwhen
28 facts verified.
trylift
     - trylift
5 facts verified.
Call counting
600 facts verified.
push! inside push!
push! called when another signal is still updating.

 in push! at /Users/Max/.julia/v0.3/Reactive/src/Reactive.jl:257
 in crash at /Users/Max/.julia/v0.3/Reactive/test/concurrency.jl:7
 in update at /Users/Max/.julia/v0.3/Reactive/src/Reactive.jl:95
 in push! at /Users/Max/.julia/v0.3/Reactive/src/Reactive.jl:286
 in anonymous at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:178
 in do_fact at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:201
 in anonymous at /Users/Max/.julia/v0.3/Reactive/test/concurrency.jl:177
 in facts at /Users/Max/.julia/v0.3/FactCheck/src/FactCheck.jl:315
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
1 fact verified.
@lift
     - @lift input expressions
     - @lift basics
     - @lift inside a function
7 facts verified.
Flatten
     - Signal{Signal} -> flat Signal
     - Initial update count
     - Current signal updates
     - Signal swap
11 facts verified.
INFO: Reactive tests passed
INFO: No packages to install, update or remove

I'm using Julia 0.3.8 on my Macbook with OS X Yosemite installed.

Maybe you could help to find a solution.

Thanks Max

**Comment by shashi** [comment]
Pkg.test("Reactive") is fine. Those errors are part of the tests :P GLPlot is failing because of changes to Reactive. cc @SimonDanisch
