### ISSUE TITLE
Trying to lift...

### ISSUE THREAD

**Issue by dehann** [JuliaLang/Reactive.jl#60]
Hi,

Maybe I'm just missing something obvious, but I'm not able to get the "lift" part of the tutorial working. I'd really like to use it! I've tried on Julia 0.3.8/10 and 0.4-dev

#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015

$ ./julia-dev
...
Version 0.4.0-dev+5696 (2015-06-29 15:30 UTC)
Commit 1544e4e* (0 days old master)
x86_64-unknown-linux-gnu

julia> Pkg.add("Reactive")
INFO: Initializing package repository /home/dehann/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Installing Compat v0.4.6
INFO: Installing FactCheck v0.2.8
INFO: Installing Reactive v0.2.2
INFO: Package database updated

julia> using Reactive

julia> x = Input(0)
0

julia> xsqr = lift(a -> a*a, Int, x)
ERROR: MethodError: `consume` has no method matching consume(::Function, ::Type{Int64}, ::Reactive.Input{Int64})
Closest candidates are:
  consume(::Task, ::Any...)
  consume(::Union{DataType,Function}, ::Reactive.Signal{T}...)
  consume(::Union{DataType,Function}, ::Reactive.SignalSource...)
 in lift at /home/dehann/.julia/v0.4/Reactive/src/Reactive.jl:362

Thanks,
Dehann

**Comment by shashi** [comment]
This is a documentation bug. Sorry about that. You should be good if you use `xsqr = lift(a -> a*a, x, typ=Int)` instead

**Comment by dehann** [comment]
Ah, got it thanks!
