### ISSUE TITLE
Allow multiple signals updating at once

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Reactive.jl#62]
When using signals heavily, it quickly becomes very annoying that only one signal can update at a time. What is the reason for this? I understand that you have to detect the same signal updating recursively, but why can't multiple independent signals update simultaneously? @shashi

**Comment by shashi** [comment]
The restriction is pretty much only there to protect from recursive updates causing an infinite loop. You're right though that allowing multiple signals to propagate simultaneously is not that big a deal although it might mess up non-commutative `foldl`s...

The _correct_ way to implement signal propagation is using channels: each signal node reads from a channel of a parent and writes to a multi-cast channel subscribed to by all its children. This would take care that ordering is proper, and each node's function can be run in a different process if need be. Do you think it's worth trying? I have no idea what the overhead is going to be like when something like this is run on a single process, as is the case in Reactive's most common use cases.

**Comment by Keno** [comment]
I don't understand why channels are required. It just seems like a per-signal isupdating flag would be enough for an initial implementation.

**Comment by shashi** [comment]
Hmm, isupdating as a boolean flag or as a Condition? I don't understand how. Could you briefly elaborate?

**Comment by Keno** [comment]
Well, I probably don't know the architecture well enough, but I was thinking just have a set of currently updating signals and don't allow push on those.

**Comment by timholy** [comment]
Here's an application where this would be nice to have: https://github.com/timholy/GtkUtilities.jl (which has a Reactive-like component that I'd prefer to switch over to being based on Reactive) has properties for setting the x- and y- zoom range on a plot. (The docs are a little out of date, the current properties are `:viewx` and `:viewy`.) When a user draws a rubber-band selection region, it would be nice to be able to `push!(:viewx, newvaluex)` without triggering a Canvas redraw until I've also done `push!(:viewy, newvaluey)`. Right now I suppose the best way to do this is just `nx.value, ny.value = newvaluex, newvaluey` and then manually running the actions associated with `nx` and `ny`.

**Comment by shashi** [comment]
How about adding a `push!{N}(::NTuple{N}, ::NTuple{N})` method?

**Comment by timholy** [comment]
Works for me.

**Comment by shashi** [comment]
I thought about implementing this, and I think this necessitates the heap that #65 got rid of.

Consider:

```julia
x = Input(1)
y = Input(2)

c = map(-, b)
d = map(tuple, a, c)
```
Initially `value(c)` = -2, `value(d)` = (1, -2)

Now say `x` and `y` both update simultaneously to (0, 0), `x` will call its actions, of which there is only one: update d, which results in d's value becoming `(0, -2)`, which is not correct.

Similar problem arises in making the updates Breadth-first with a queue -- the children of `a` and `b` together are in the sequence [`d`, `c`] - but at each step you need the "oldest" node, in this case that is `c`, which means the stack really should be a heap ordered by the oldest first.

I'm now wondering if this is worth the overhead.

Either way, I think  the correct way to tackle your specific problem of updating the plot is to use `throttle`:

```julia
dimension = throttle(0.016, map(tuple, viewx, viewy))
```

Now, `dimension` will update at most once every 16ms, (note that it does so asynchronously 16ms after the latest update). This takes care of smoothing immediate updates of both x and y, and goes even further to throttle the updates to 16ms, which gets you 60fps animation with the least amount of work required.

**Comment by timholy** [comment]
`throttle` sounds like a nice solution---I wasn't aware of its existence. (In general I need to spend more time learning about the built-in operators.) Glancing at the implementation, it should do exactly what I need.

**Comment by shashi** [comment]
You can now have many `push!`s at the same time, they all end up in a central queue. If you don't want a blocking operation to stop the signal graph in its tracks, consider using [`async_map`](https://github.com/JuliaLang/Reactive.jl/blob/fcda6c34e55de192ce8e20138e357e026f807d3f/src/async.jl#L5-L8)
