### ISSUE TITLE
foldl uses more state than necessary?

### ISSUE THREAD

**Issue by mtikekar** [JuliaLang/Reactive.jl#68]
For example, to delay a signal -
```julia
function delay_func(state, value)
    older_value, prev_value = state
    return (prev_value, value)
end

delay(init_value, signal) = map(x -> x[1], foldl(delay_func, (0, init_value), signal))
```
It seems that `older_value` is unnecessary. To compare with Elm,

```elm
delay init_value signal = foldp (\value state -> value) init_value signal
```

One way around is to define a `foldp` using `foldl`, but then I wonder why `foldl` and its extra state is needed in the first place.

**Comment by shashi** [comment]
Are you sure that snippet works in Elm? http://www.share-elm.com/sprout/55ec88d2e4b0ff56ab759561

You still need the tuple to carry over previous state.

foldl in Reactive is the same as foldp in Elm.

**Comment by mtikekar** [comment]
Ah, my bad. So only one element of the tuple counts towards the state. The other element is actually just an "output" signal.

I'm trying to use Reactive to model digital circuits and state machines (where not all signals count towards the state of the system). The resolution (in my understanding) is that foldl implements a [Mealy machine](https://en.wikipedia.org/wiki/Mealy_machine) and not a [Moore machine](https://en.wikipedia.org/wiki/Moore_machine). 

Thanks for the prompt response!

**Comment by shashi** [comment]
What you are looking for may be a different kind of delay, one that updates *after* the current `push!` is through. You may be interested in trying `delay` function in the `next` branch which is an upcoming release of this package. You can run `Pkg.checkout("Reactive", "next")` to get this.
