### ISSUE TITLE
Error: "Patchable not defined" under Julia 0.4.0

### ISSUE THREAD

**Issue by tgenewein** [JuliaLang/Reactive.jl#71]
The following code runs fine under Julia 0.3.10 but it produces an error under Julia 0.4.0
```
using Interact, Reactive, Gadfly

sl_β = slider(0:1:50, label="Npoints")    
display(sl_β) #displays the slider at the output of the current cell

#tie the slider with the plotting routine
plt_pa = lift(β->begin
                    plt_pagw = plot(x=rand(β),y=rand(β),Geom.point, Geom.line)
                 end,sl_β)
```

The output in Julia 0.4.0 is
```
UndefVarError: Patchable not defined

 in anonymous at D:\JuiliaPackages\v0.4\Gadfly\src\Gadfly.jl:891
 in lift at D:\JuiliaPackages\v0.4\Reactive\src\Reactive.jl:364
 in writemime at D:\JuiliaPackages\v0.4\Gadfly\src\Gadfly.jl:891
 in sprint at iostream.jl:206
 in display_dict at D:\JuiliaPackages\v0.4\IJulia\src\execute_request.jl:39
```
I'm running this on the release of Julia 0.4.0 and I have checked out the Interact.jl master - here's the specific package versions I'm using
```
 - Gadfly                        0.3.17
 - IJulia                        1.1.7
 - Interact                      0.2.1+             master
 - Patchwork                     0.1.8
 - Reactive                      0.2.4
```

Thanks for having a look into this!

**Comment by rohitvarkey** [comment]
I don't think this is a Reactive issue. And you have `Compose` also installed right?

**Comment by shashi** [comment]
delete ~/.julia/v0.4/libs/Compose.ji and try again

https://github.com/dcjones/Compose.jl/blob/master/src/Compose.jl#L161-L163 might have been false the last time you recompiled Compose

tagging Compose should automatically fix this issue cc @dcjones

**Comment by tgenewein** [comment]
Unfortunately I can't access the original machine with the bug until next TUE, however, I tried again on another machine starting from scratch with julia 0.4. and then adding packages (including Patchwork) - now the code runs fine.

I'll close the issue as it's solved and is not a Reactive issue.  Just to be sure I'll try the suggestion of @shashi on the buggy machine as well as soon as I get to it.

Thanks a lot for helping out!

**Comment by tgenewein** [comment]
Just for the sake of completeness - deleting the precompiled ``Compose.ji`` as described above also did the trick. With the recompiled version everything runs fine.
