### ISSUE TITLE
Depwarns suggest Node rather than Signal

### ISSUE THREAD

**Issue by sjkelly** [JuliaLang/Reactive.jl#78]
In #65 the consensus was that the exported name for `Node` should be `Signal`.

I am seeing:
```
Reactive.Input is deprecated, use Reactive.Node instead
```

**Comment by shashi** [comment]
This is a limitation of `@deprecate_binding` and happens because `Signal` is a typealias of `Node`. I tried to workaround it but didn't succeed.

**Comment by timholy** [comment]
I bet the only way to solve that problem is to use `Signal` internally.

**Comment by shashi** [comment]
You're right.
