### ISSUE TITLE
Problems with Gtk

### ISSUE THREAD

**Issue by jverzani** [JuliaLang/Reactive.jl#93]
I filed an issue https://github.com/JuliaLang/Gtk.jl/issues/229 indicating that Gtk and Reactive no longer play nicely together. Any thoughts as to why?

**Comment by anriseth** [comment]
The problem mentioned in jverzani/GtkInteract.jl#11 is introduced with Reactive commit 6a50bcd

**Comment by shashi** [comment]
@jverzani could you check if #94 fixes this?

**Comment by anriseth** [comment]
@shashi #94 fixed it for me.

**Comment by jverzani** [comment]
Yes it works for me too. Many thanks! I still have this more obscure issue https://github.com/JuliaLang/Gtk.jl/issues/208 but that is a pretty minor thing.
