### ISSUE TITLE
100% CPU after using Reactive

### ISSUE THREAD

**Issue by zsoltveraszto** [JuliaLang/Reactive.jl#95]
using Reactive 
in Julia REPL causes constant 100% CPU utilization. rebuilding, removing, adding the package again does not help. What can be the problem?

versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

zsolt

**Comment by shashi** [comment]
Did you try running the master branch of Reactive?

**Comment by zsoltveraszto** [comment]
No, so Pkg.checkout saved me, now I can use Reactive & Escher again, thank you very much!
